# Generated by Django 2.0.2 on 2018-03-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='ToDo',
        ),
    ]
