# Generated by Django 2.0.2 on 2018-03-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20180323_1636'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='does',
        ),
    ]
