# Generated by Django 2.0.2 on 2018-03-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_auto_20180323_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'does'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
